### ISSUE TITLE
Missing image in notebook 1

### ISSUE THREAD

**Issue by ptizei** [elzurdo/multi_objective_optimisation#5]
In the markdown cell between code cells 17 and 18, there's a broken image just under the pic of the horse with the blinders (Screenshot below).

The link seems to be to something in google images, which might get dynamically allocated to avoid hot-linking like this. Might be best to download it and then upload somewhere you can ensure it gets a fixed URL.

![image](https://user-images.githubusercontent.com/32848050/97813307-f9041100-1c65-11eb-9af0-fd4f67c18ac7.png)

**Comment by elzurdo** [comment]
thanks.  done!
